### Update an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174001
Content-Type: application/json

{
  "name" : "Jane Sena Smith",
  "email" : "janesena.smith@example.com",
  "address" : "456 Elm St, Shelbyville",
  "dateOfBirth": "1990-09-23"
}
###